// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Vite inlines import.meta.env.* at build time for the client bundle.
  // In the SSR bundle, Vite replaces import.meta.env with process.env references.
  // We use a single canonical name: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.
  const SUPABASE_URL = (import.meta.env as Record<string, string | undefined>).VITE_SUPABASE_URL;
  const SUPABASE_ANON_KEY = (import.meta.env as Record<string, string | undefined>)
    .VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing: string[] = [];
    if (!SUPABASE_URL) missing.push("VITE_SUPABASE_URL");
    if (!SUPABASE_ANON_KEY) missing.push("VITE_SUPABASE_ANON_KEY");
    const message = `[Supabase] Missing environment variable(s): ${missing.join(", ")}. Add them to your Vercel Environment Variables (Settings → Environment Variables) and redeploy.`;
    console.error(message);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Eagerly create the client on the browser so auth session is recovered from localStorage.
// On the server (SSR), we leave it lazy because localStorage does not exist.
if (typeof window !== "undefined") {
  _supabase = createSupabaseClient();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
